[package]
name = "sc"
version = "0.1.0"
edition = "2021"


[dependencies]
tui = "0.19.0"
crossterm = "0.25"
ical = "0.7.0"
ureq = "2.5.0"
fxhash = "0.2.1"
clap = { version = "4.0.6", features = ["cargo"] }
time = "0.3.14"
dirs = "4.0"
spinners = "4.1.0"